### ISSUE TITLE
Some results have Coverage>100%

### ISSUE THREAD

**Issue by HongyuanChu** [HuiyangYu/PanDepth#6]
Command line:
pandepth -i /data/chuhy/project/Hg/HG002_GRCh38_ONT-UL_GIAB_20200122.phased.bam -o /data/chuhy/project/Hg/pandepth/Hg002 -t 5 
![20fbc592b4d0c6fbd6410dcf6d60689](https://github.com/HuiyangYu/PanDepth/assets/158466423/6d7c3778-f82f-4d7e-b48f-e4cc611be4ec)
Some results have Coverage>100%.

**Comment by HuiyangYu** [comment]
Which version are you using?

**Comment by HongyuanChu** [comment]
I am using PanDepth-2.24-Linux-x86_64;
If adding a bed file 
pandepth -i /data/chuhy/project/Hg/HG002_GRCh38_ONT-UL_GIAB_20200122.phased.bam -o /data/chuhy/project/Hg/pandepth/Hg002 -b HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed
It would not >100% anymore

**Comment by HuiyangYu** [comment]
Can you provide a download link for the UL ont of HG002 as well as the reference genome? Also the commands you alignment are needed. I would try to reproduce your results as closely as possible and then look for the exact bug.

**Comment by HongyuanChu** [comment]
Thank you very much!
#bam:
http://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/guppy-V3.2.4_2020-01-22/HG002_GRCh38_ONT-UL_GIAB_20200122.phased.bam
#bed
https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed

**Comment by HongyuanChu** [comment]
The bam files were standard samples from GIAB. 
Reads were separately aligned to both hs37d5 and hg38 human genome reference assemblies using Heng Li's minimap2
(https://github.com/lh3/minimap2) with the following options:

    -a -z 600,200 -x map-ont
As shown in https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/guppy-V3.2.4_2020-01-22/README

**Comment by HuiyangYu** [comment]
I apologize for the delayed response. We have identified the cause of the bug. In order to conserve memory usage, PanDepth employs a sliding window approach for calculation when detecting the index of bam/cram files. However, this method presents an issue: if the window size is set too small, certain reads may span multiple windows, particularly when a read contains numerous or very long insertions or deletions. As a result, some genomic positions are likely to be redundantly calculated, leading to coverage values exceeding 100%. To comprehensively address this issue and further enhance the multi-threading efficiency of PanDepth, we have decided to perform a complete code refactoring. However, this process may require a substantial amount of time to complete. <br>As a temporary solution to your issue, you can rename the index file suffix of the bam from 'bai' to another name, such as 'baix', and then recalculate. This will yield the correct results. <br> It should be noted that when performing calculations without using the index, you can still enable multi-threading. However, setting '-t' to a value exceeding 5 will not further improve computational efficiency.

**Comment by HongyuanChu** [comment]
Thank you so much for your timely and useful reply!

**Comment by HuiyangYu** [comment]
This is the result of the coverage calculation using Samtools, which took 160 minutes to complete. (If feasible, we can temporarily keep this issue open so that I can inform you promptly upon completing the code refactoring.)
![image](https://github.com/HuiyangYu/PanDepth/assets/41780741/81db3cea-7431-4d2a-a381-ed6f999691ea)

**Comment by hewm2008** [comment]
We have found a solution to the problem and will release version 2.25 today （or tomorrow ）  after the test has no problems

**Comment by HuiyangYu** [comment]
This is the result of the calculation by version 2.25 using the index for the ONT BAM file.
<img width="673" alt="1716356676831" src="https://github.com/HuiyangYu/PanDepth/assets/41780741/c2fc5d91-3d75-4825-b983-3b4c3de37dcb">
